= Databases

JPA can work with any relational SQl database. For all common database
products there is already an adapter. If you need to connect to some
strange datasource, you could in theory write your own adapter,
but that's way out of scope for this week. Here we focus on the two
SQL databases that we do use.

== H2

H2 is a small, fast, serverless (self-contained)
SQL database written in Java that runs entirely in-VM. It is thus very useful for
unit testing
(remember, Unit Tests are supposed to be small, fast and self-contained).
We use H2 for the tests in most of the projects.
It's called H2 because it is an outgrowth of the earlier Hypersonic.

== PostgreSQL

Postgresql is an open source SQL database that is closer in spirit and syntax
to Oracle and, IMHO, both closer to the SQL standard, more sensible, and
more robust, compared to other open-source databases. 
The server runs as a daemon on Unix/Linux/Mac and as a Service on MS-Windows.

There are two interfaces to PostgreSQL, the command-line psql and the gui.

PSQL is a command-line command that is on your path. 
Like most command-line interfaces, PSQL is much faster than the GUI,
but requires you to know a few things. 
Its input consists of a mixture of SQL commands
(which may include Data Definition (DDL) commands like _create table;_),
and psql-specific commands that begin with a backslash - \d for Describe,
\q for Quit, and so on.
Try the following:

	psql -d jpademo
	\l
	\d
	\d mydemotable
	select * from mydemotable;
	\?
	\q

You can ignore any messages about "code page" issues if you don't
use what Anglophones consider 'accented characters'.
Note that _psql_ includes its own command history mechanism using the
arrow keys.

The GUI interface is started from the Start Menu, under PostgreSQL 10,
choose the pgAdmin application. Expand the Servers list at the left,
then drill down to Databases, then jpademo, then Schemas, then public,
then tables, and you can view or modify the tables in the jpademo database.

We used psql to set up the persistent databases, as follows:

	psql <<!
	create user student password 'student' login nosuperuser;
	create database ticketmanor owner student;
	create database custfeedback owner student;
	create database jpademo owner student;
	create database jpa_basic owner student;
	create database jpa_inheritance owner student;
	create database jpa_aggregation owner student;
	!

These databases are used as follows:

[[Databases]]
.The Persisten Databases
[options="header",cols="2,4,5"]
|====
|DB name|Server DataSource|Description
|ticketmanor|TicketManorDataSource|Main TicketManor demo db
|jpademo|n/a|jpademo project
|jpa_basics|N/A|HO 3.x
|jpa_aggregation|N/A|HO4.1
|jpa_inheritance|N/A|HO4.2
|CustFeedback|CustFeedbackDataSource|Customer Feedback (ex5.3)
|====


