= CourseFiles936

This directory contains the web pages and most of the exercise projects for
http://learningtree.com[Learning Tree]'s
http://learningtree.com/936[Course 936, Enterprise Java Applications: JSF, EJB3, JSF and AJAX].

There is one other adjacent folder, TicketManorJava, which is hosted on 
LearningTree's GitHub account, https://github.com/LearningTree/TicketmanorJava/.

There are several adjacent folders: jsfdemo jpademo clublist javasrc.
Those other projects are hosted on the course author's github, at
https://github.com/IanDarwin/.

== Setup

To set up the environment at home or work, you should try the following:

. Make sure you have Java 8, Maven 3 installed and on your PATH.
. Git clone all the projects listed above into the same directory (in the course we use C:\ but anyplace *should* work).
. Rename CourseFiles936 CourseFiles
. Run the uber-script: `cd Coursefiles; sh scripts/all-in`
The script produces tons of output so it is set to fail on the first error.

----
for d in LearningTree/TicketManorJava IanDarwin/{CourseFiles936,jsfdemo,jpademo,clublist,darwinsys-api,javasrc}
do
	git clone https://github.com/$d
done
mv CourseFiles936 CourseFiles
----
