= CourseFiles936

This directory _CourseFiles936_ contains the web pages and exercise projects for
http://learningtree.com[Learning Tree]'s
http://learningtree.com/936[Course 936, Enterprise Java Applications: JSF, EJB3, JSF and AJAX].

The _sourcecode_ subdirectory of the current folder is intended to be the root of an Eclipse Workspace

This is for the J.1 Revision (Jan 2018); *do not* try to use this earlier versions as the directory structure has changed.

All code is copyright (C) by Learning Tree International.

This code won't do you much good unless you're taking the course.

There is one other adjacent folder, TicketManorJava, which is hosted on 
LearningTree's GitHub account, https://github.com/LearningTree/TicketmanorJava/.

There are several adjacent folders hosted on the author's github,
https://github.com/IanDarwin/, including jsfdemo jpademo clublist javasrc.
There is also the _makehandsons_ project which makes the hands-on exercises from 
the solutions, so they are always in synch.

== Set Up the environment at home or work

To set up the environment at home or work, you should try the following
(the implementing command examples are for Unix, Linux, Mac OS X,
and might work on MS-Windows with CygWin or equivalent):

* Make sure you have 
Java SE (8 or 9), 
Maven 3 (https://maven.apache.org), 
a database (https://postgresql.org/)
and _git_ (https://git-scm.com/)
installed and on your PATH.
* Make sure you have Wildfly installed but not running;
you could use a different App Server but you'd have to change
all the Maven deployment configurations (they have GlassFish and Tomcat in place but unmaintained!!)
AND the DataSource configurations (alas, the EE spec doesn't nail down how to do this).
* Poor MS-Windows users must also install cygwin, including git and diff.
* Git clone all the projects listed above into a single parent directory (in the course we use C:\ but anyplace *should* work).
----
cd WHERE_YOU_WANT_IT
for repo in LearningTree/TicketManorJava \
	IanDarwin/{CourseFiles936,clublist,javasrc,darwinsys-api,jsfdemo,jpademo,cdi-ee-samples,makehandsons,createprojects}
do
    git clone https://github.com/$repo
done
----
* Copy or merge Coursefiles936/configs/standalone-full.xml into wildfly
* Start Wildfly: cd WILDFLY_HOME; bin/standalone -c standalone-full.xml
* If it doesn't start successfully, iterate on your configuration.
* Run the uber-script:
----
cd Coursefiles936
sh scripts/all-in
----
The script produces tons of output so it is set to fail on the first error,
otherwise error messages would be missed.

=== Eclipse Workspace Setup

The normal intention is that the _sourcecode_ subdirectory should be the base of an Eclipse workspace.
We don't yet have this set up automatically so please do the following:

* Start Eclipse
* If it opens an existing workspace, do File->Switch Workspace. If not it will ask you for the workspace.
* Browse to where you downloaded CourseFiles936, and select (but don't double click on) CourseFiles936/sourcecode. Click OK.
* Then do File->New Project->new Java Project, browse to the TicketManorJava folder, select but don't double-click
on datamodel,
which should cause the dialog to change the text in its bottom panel to something like
 "The wizard will use the existing settings to configure the project". Click Finish.
* Repeat the above for the ticketmanor-ee project.
* Then for each Exercise you want, do File->New Project->New Java Project, and select the _exNN_ folder
and follow the same procedure as for ticketmanor-ee.
* Do the similar operation for any Solution project you want.
* Ditto for jsfdemo, jpademo, and clublist except they should be in the folder one level up in the filesystem.
* If you want the javasrc project (code examples from the Java Cookbook) and darwinsys-api (some helper files),
do the same for them.

At this point you should have things pretty much set up as in the course.

=== Other IDE Workspace Setup

We don't provide instructions for other IDEs. If you get it working in a way that doesn't 
interfere with it working with Eclipse and Maven, please feel free to send a Github pull request,
