== Troubleshooting

=== Maven Deployment

When you run _mvn wildfly:deploy_ you should see the message "Build Success" near the end of the Maven output.
If not, check the following:

. Are you in the correct directory? Each directory has its own directory. If you invoke Maven in a directory without a pom.xml, you will see this:
----
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory.
Please verify you invoked Maven from the correct directory. -> [Help 1]
----
. Is it a compilation error? If so, fix your code and try again.
. Did any tests fail? If so, correct the code (or the test) and try again.
. Is it a deployment error?  These will look like this:
----
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.2.Final:deploy (default-cli) on project ticketmanor-javaee: Deployment failed and was rolled back. -> [Help 1]
----

If so, look in the console window where JBoss is running.
This output is pretty verbose, but the error will usually be called out somewhere in the
last hundred lines or so. In particular, look for a Java stack trace.
With practice, the errors will become easier to track down here.

==== Maven: Bad Advice

On most Maven failures, Maven will print this helpful advice:
----
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
----
99.45% of the time you should just ignore this. Seeing a stack trace of Maven's
internals isn't that interesting.

==== JMS Issues With WildFly

When you run ex42's CommentSender, you should see something like this:

----
1 20:38:57,478 INFO  [org.jboss.as.server] (management-handler-thread - 1) JBAS018559: Deployed "ex42solution-1.0.0-SNAPSHOT.war" (runtime-name : "ex42solution-1.0.0-SNAPSHOT.war")
2 20:39:22,813 INFO  [stdout] (Thread-1 (HornetQ-client-global-threads-1648300319)) Got sender: Whiney Whitefoot--ww@gmail.moc
 20:39:22,813 INFO  [stdout] (Thread-1 (HornetQ-client-global-threads-1648300319)) Got comment: I actually love your site!!
3 20:39:22,814 INFO  [stdout] (Thread-1 (HornetQ-client-global-threads-1648300319)) Hibernate: call next value for hibernate_sequence
4 20:39:22,818 ERROR [stderr] (Thread-1 (HornetQ-client-global-threads-1648300319)) Feedback saved to database!
5 20:39:22,825 INFO  [stdout] (Thread-1 (HornetQ-client-global-threads-1648300319)) Hibernate: insert into FeedbackForm (comment, custEmail, custName, date, id) values (?, ?, ?, ?, ?)
6 20:39:22,808 ERROR [stderr] (Thread-2 (HornetQ-client-global-threads-1648300319)) Wanted ObjectMessage but got sent a org.hornetq.jms.client.HornetQTextMessage
7 20:39:22,831 INFO  [org.jboss.as.naming] (default task-7) JBAS011806: Channel end notification received, closing channel Channel ID 52f7aa52 (inbound) of Remoting connection 573c6231 to /127.0.0.1:50304
----

. Is the normal deployment message
. Several debug printlns from CommentReceiver (format varies as you wrote this) dumping the form
. JPA Provider (Hibernate) getting ready to insert
. Output from CommentReceiver after giving data to JPA 
. JPA Provider trace of the insert
. This *looks like an error but is supposed to be there*; _it is there
to test your error handling_, and comes from the second "send" 
that you are asked to do in CommentSender
. We closed the Session, so the other end gets notified and cleans up.

Note that because of threading, the lines can appear in almost any order.
In fact, line 6 often appears before line 2, because its thread has much less to do
and finishes more quickly!

If you get anything terribly different, please ask your instructor. Notice
also the JBoss will sometimes tell you it's re-deployed your JMS but
apparently not actually do so; add a debug statement and see if the line
numbers in the stack trace are affected. If not, we have to stop the server,
find and remove the deployment element near the end of
WILDFLY_HOME/standalone/configuration/standalone-full.xml, re-start the server,
and re-deploy the application.
