#!/bin/sh

# Update and build all repos while online.

# Must run in a git-bash or equivalent real shell environment

# DO NOT RUN mid-week as it will wipe out some or all of the student's work!!!

GIT_DIRS="TicketManorJava CourseFiles javasrc jpademo jsfdemo clublist makehandsons"
INSTALL_DIRS="TicketManorJava/datamodel TicketManorJava/ticketmanor-ee makehandsons"
TEST_DIRS="CourseFiles/sourcecode/*solution javasrc jpademo jsfdemo clublist makehandsons"

# These two CD's are intentional, test on Unix, run on Bash-on-Windows.
cd
cd C:/

# Excepting the two CD commands, nothing else must fail
set -e

for repo in ${GIT_DIRS}
do
	(
	cd ${repo}
	echo === $repo ===
	git pull
	)
done


# Install things we need installed
for dir in ${INSTALL_DIRS}
do
	(
	cd ${dir}
	echo === $dir ===
	mvn clean install
	)
done

(
cd CourseFiles/sourcecode
../../makehandsons/scripts/makehandsons *solution
)

# Run Maven Test in remaining, which ensures the pre-reqs are present.
for proj in ${TEST_DIRS}
do
	(
	cd $proj
	echo === $repo ===
	# Build with Maven
	mvn clean test
	)
done

