#!/bin/sh

# pull all git repos, and do post-synchronization tasks

# Must run in a git-bash or equivalent real shell environment

# DO NOT RUN mid-week as it will wipe out some or all of the student's work!!!


cd C:/

for repo in TicketManorJava CourseFiles javasrc jpademo jsfdemo clublist makehandsons
do
	(
	cd $repo
	git pull
	)
done

(
cd TicketManorJava/datamodel
mvn install
)

(
cd makehandsons
mvn install
)

(
cd CourseFiles/sourcecode
../../makehandsons/scripts/makehandsons *solution
)
