#!/bin/sh

# Try to put a machine back to initial state

# These two CD's are intentional, test on Unix, run on Bash-on-Windows.
cd
cd C:/

# Excepting the two CD commands, nothing else must fail
set -e

(
echo "Un-modify these config files..."
cd wildfly/standalone/configuration
vi application*.properties
echo Now delete all deployments from end of file...
vi standalone-full.xml
# XXX make this a straight cp operation.
)

(
cd TicketManorJava
git checkout -- ticketmanor-ee
)

(
cd jpademo
git checkout -- src/main/
)

(
cd CourseFiles936/sourcecode
rm -r */target/
)
