= Updating Load Machine from 936H.2 to 936H.3

Things to do on the load or your dev machine when upgrading.

General: set up the command prompt to start in CourseFiles.

Close eclipse.

cd CourseFiles

git pull # megadiffs

Run bash scripts/all-in to regenerate and test almost everthing. Runs for a while...

start Eclipse

Window->Prefs->JBoss Tools->JBoss Central - uncheck Show at Startup. Click OK

remove junitbasic, ex41bonus, ex41bonussolution - both from eclipse and from the filesystem!

New->Java Project at donow21 (replaces junitbasic), donow21solution, ex43, ex43client, ex43solution, ex43clientsolution
# MAKE SURE each one says "The wizard will configure..." after you type the last character!

Refresh in all projects (esp ex81solution which is a total rewrite

If ADT/AndMore is installed, and you get a popup when you run a unit test:
	Select Change Workspace Settings, set JUnit Run and Debug launcher to Eclipse. 

New feature: in sourcecode, do mvn compile, it will test that all the solutions compile.
(Probably redundant with what "all-in" does, but hey...).

Should be all. I hope.
